build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

  script:
    - git clone --recursive https://gitlab.com/shaktiproject/software/shakti-tools.git"
    - source ./setenv.sh
    - env
    - make all
    - make all TARGET=artix7_100t

  tags:
    - sw-runner